### ISSUE TITLE
Autodetect wrong layout

### ISSUE THREAD

**Issue by projct1** [ai/convert-layout#30]
Hi)
How i can autodetect what i need: toEn or fromEn?
If i type `htcnjhfy` => its `fromEn` (ресторан)
But if i type `restoran` => i dont need use `fromEn`.

**Comment by ai** [comment]
This task is complicated and out of the use case for this library.

This library is for English-only fields like `Cardholder Name`. You need Punto Switcher analog which will request a very big database in JS bundle.
